name: 'Hello World Action'
description: 'In ra lời chào với tên được truyền vào'

inputs:
  name: # Đây là "string name" bạn muốn nhận vào
    description: 'Tên của người cần chào'
    required: true
    default: 'World'

outputs:
  greeting-message:
    description: 'Lời chào đầy đủ'
  vietnam-greeting:
    description: 'Lời chào Việt Nam'

runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.name }}"
      shell: bash

    - name: Set greeting outputs
      shell: bash
      run: |
        full_greeting="Hello ${{ inputs.name }}! Welcome to GitHub Actions"
        vn_greeting="${{ inputs.name }} - xin chào việt nam"
        
        # Set outputs cho composite action
        echo "greeting-message=$full_greeting" >> $GITHUB_OUTPUT
        echo "vietnam-greeting=$vn_greeting" >> $GITHUB_OUTPUT