name: 'Hello World Action'
description: 'In ra lời chào với tên được truyền vào'

inputs:
  name: # Đây là "string name" bạn muốn nhận vào
    description: 'Tên của người cần chào'
    required: true
    default: 'World'

outputs:
  greeting-message:
    description: 'Lời chào đầy đủ'
    value: ${{ steps.generate.outputs.greeting-message }}
  vietnam-greeting:
    description: 'Lời chào talk'
    value: ${{ steps.generate.outputs.vietnam-greeting }}

runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.name }}"
      shell: bash

    - name: Set greeting outputs
      shell: bash
      run: |
        full_greeting="Hello ${{ inputs.name }}! Welcome to GitHub Actions"
        vn_greeting="${{ inputs.name }} - xin chào talk"
        
        # Set step outputs (không phải action outputs)
        echo "greeting_message=$full_greeting" >> "$GITHUB_OUTPUT"
        echo "vietnam_greeting=$vn_greeting" >> "$GITHUB_OUTPUT"
        
        # Debug log
        echo "Generated: $full_greeting"
        echo "Generated VN: $vn_greeting"