
name: Stage Build Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  test-stage-build:
    strategy:
      matrix:
        # Định nghĩa danh sách môi trường
        env: [staging, production]
      max-parallel: 1 # Để staging chạy xong mới tới production (tùy chọn)
    
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }} # Tự động đổi theo lượt chạy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Database Logic
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_HOST }}
          APP_URL_INTERNAL: ${{ vars.APP_URL }}
        run: |
            echo "--- KIỂM TRA MÔI TRƯỜNG ${{matrix.env}} ---"
            echo "Dữ liệu Variable (Hiện rõ): $APP_URL_INTERNAL"
            echo "Dữ liệu Secret (Sẽ hiện ***)"

            if [ -z "$DB_CONNECTION_STRING" ]; then
                echo "❌ LỖI: Không tìm thấy Secret DATABASE_URL ở Production"
            else
                echo "✅ ĐÃ KẾT NỐI: Secret DATABASE_URL có tồn tại"
            fi

            python check-workflow.py    